spring:
  datasource:
    url: jdbc:h2:mem:maindb
    initialization-mode: never

  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: validate

    properties:
      hibernate:
        format_sql: true

    show-sql: true
  data:
    rest:
      base-path: /datarest

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
  health:
    defaults:
      enabled: true

logging:
  level:
    ROOT: ERROR
  file:
    name: application.log